#!/usr/bin/env node

/**
 * Offline Functionality Test Script
 * 
 * This script tests the offline AI services and local storage functionality
 * without requiring a full server setup.
 */

const fs = require('fs');
const path = require('path');

// Test configuration
const TEST_CONFIG = {
  audioFile: './test-audio.mp3', // Place a test audio file here
  personName: 'Test Person',
  userId: 'test-user-123'
};

async function testOfflineServices() {
  console.log('🧪 Testing Offline Dementia Care Services...\n');

  try {
    // Test 1: Check if offline AI service can be imported
    console.log('1️⃣ Testing Offline AI Service Import...');
    const offlineAiService = require('./server/services/offlineAiService');
    console.log('✅ Offline AI Service imported successfully');

    // Test 2: Check if local storage service can be imported
    console.log('\n2️⃣ Testing Local Storage Service Import...');
    const localStorageService = require('./server/services/localStorageService');
    console.log('✅ Local Storage Service imported successfully');

    // Test 3: Check if cleanup service can be imported
    console.log('\n3️⃣ Testing Cleanup Service Import...');
    const cleanupService = require('./server/services/cleanupService');
    console.log('✅ Cleanup Service imported successfully');

    // Test 4: Test local storage initialization
    console.log('\n4️⃣ Testing Local Storage Initialization...');
    const storageStats = await localStorageService.getStorageStats(TEST_CONFIG.userId);
    console.log('✅ Local Storage initialized successfully');
    console.log(`   Storage path: ${storageStats.storagePath}`);

    // Test 5: Test offline AI service initialization (if Ollama is available)
    console.log('\n5️⃣ Testing Offline AI Service Initialization...');
    try {
      await offlineAiService.initializeServices();
      console.log('✅ Offline AI Service initialized successfully');
    } catch (error) {
      console.log('⚠️  Offline AI Service initialization failed (Ollama may not be running)');
      console.log(`   Error: ${error.message}`);
    }

    // Test 6: Test conversation storage (mock data)
    console.log('\n6️⃣ Testing Conversation Storage...');
    const mockConversation = {
      _id: `test-conv-${Date.now()}`,
      userId: TEST_CONFIG.userId,
      personName: TEST_CONFIG.personName,
      audioPath: '/mock/path/audio.mp3',
      transcript: 'This is a test conversation transcript.',
      summary: 'Test conversation summary generated by offline AI.',
      keyTopics: ['testing', 'offline', 'ai'],
      emotions: [{ emotion: 'neutral', confidence: 0.8 }],
      sentiment: 'neutral',
      sentimentScore: 0.1,
      keywords: ['test', 'conversation', 'offline'],
      duration: 30,
      language: 'en',
      processingStatus: 'completed',
      metadata: {
        recordingDevice: 'test',
        audioQuality: 'high',
        backgroundNoise: 'low',
        speakerCount: 2
      }
    };

    await localStorageService.saveConversation(TEST_CONFIG.userId, mockConversation);
    console.log('✅ Mock conversation saved successfully');

    // Test 7: Test conversation retrieval
    console.log('\n7️⃣ Testing Conversation Retrieval...');
    const conversations = await localStorageService.getConversations(TEST_CONFIG.userId);
    console.log(`✅ Retrieved ${conversations.conversations.length} conversations`);
    
    if (conversations.conversations.length > 0) {
      const conversation = conversations.conversations[0];
      console.log(`   Latest conversation: ${conversation.personName} - ${conversation.summary.substring(0, 50)}...`);
    }

    // Test 8: Test cleanup service stats
    console.log('\n8️⃣ Testing Cleanup Service Stats...');
    const cleanupStats = await cleanupService.getCleanupStats();
    console.log(`✅ Cleanup service stats retrieved`);
    console.log(`   Total users: ${cleanupStats.totalUsers}`);
    console.log(`   Retention period: ${cleanupStats.retentionMonths} months`);

    // Test 9: Test keyword extraction (offline)
    console.log('\n9️⃣ Testing Offline Keyword Extraction...');
    const testText = 'This is a test conversation about family, health, and daily activities.';
    const keywords = await offlineAiService.extractKeywords(testText);
    console.log(`✅ Keywords extracted: ${keywords.join(', ')}`);

    // Test 10: Test emotion analysis (offline)
    console.log('\n🔟 Testing Offline Emotion Analysis...');
    const emotions = await offlineAiService.analyzeEmotions(testText);
    console.log(`✅ Emotions analyzed: ${emotions.overallSentiment}`);
    console.log(`   Detected emotions: ${emotions.emotions.map(e => e.emotion).join(', ')}`);

    console.log('\n🎉 All offline tests completed successfully!');
    console.log('\n📋 Summary:');
    console.log('   ✅ All services can be imported');
    console.log('   ✅ Local storage is working');
    console.log('   ✅ Mock conversation saved and retrieved');
    console.log('   ✅ Offline AI processing is functional');
    console.log('   ✅ Cleanup service is operational');

    console.log('\n🚀 Your offline setup is ready to use!');
    console.log('\nNext steps:');
    console.log('1. Start Ollama: ollama serve');
    console.log('2. Pull a model: ollama pull llama3.1:8b');
    console.log('3. Start the server: cd server && npm run dev');
    console.log('4. Start the client: cd client && npm run dev');

  } catch (error) {
    console.error('\n❌ Test failed:', error.message);
    console.error('\n🔧 Troubleshooting:');
    console.error('1. Make sure you\'re running from the project root directory');
    console.error('2. Install dependencies: npm run install-all');
    console.error('3. Check that all required files exist');
    console.error('4. Verify Node.js version (18+ required)');
    
    process.exit(1);
  }
}

// Test audio file processing (if test file exists)
async function testAudioProcessing() {
  if (fs.existsSync(TEST_CONFIG.audioFile)) {
    console.log('\n🎵 Testing Audio Processing...');
    try {
      const offlineAiService = require('./server/services/offlineAiService');
      const audioBuffer = fs.readFileSync(TEST_CONFIG.audioFile);
      
      console.log('📁 Test audio file found, processing...');
      const result = await offlineAiService.processConversation(
        audioBuffer, 
        path.basename(TEST_CONFIG.audioFile), 
        TEST_CONFIG.personName
      );
      
      console.log('✅ Audio processing completed!');
      console.log(`   Transcript: ${result.transcript.substring(0, 100)}...`);
      console.log(`   Summary: ${result.summary.substring(0, 100)}...`);
      console.log(`   Sentiment: ${result.sentiment} (${result.sentimentScore})`);
      console.log(`   Duration: ${result.duration} seconds`);
      
    } catch (error) {
      console.log('⚠️  Audio processing test failed (this is expected without Ollama)');
      console.log(`   Error: ${error.message}`);
    }
  } else {
    console.log('\n📁 No test audio file found (./test-audio.mp3)');
    console.log('   To test audio processing, place an audio file at ./test-audio.mp3');
  }
}

// Run tests
async function main() {
  console.log('🧠 Dementia Care - Offline Functionality Test\n');
  console.log('This script tests the offline AI services and local storage.');
  console.log('Make sure you\'re in the project root directory.\n');

  await testOfflineServices();
  await testAudioProcessing();
  
  console.log('\n✨ Testing complete!');
}

// Handle command line arguments
if (require.main === module) {
  main().catch(console.error);
}

module.exports = {
  testOfflineServices,
  testAudioProcessing
};
